# Generated by Django 3.2.4 on 2023-09-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproduct',
            name='product_pic',
            field=models.ImageField(null=True, upload_to='static/product/'),
        ),
        migrations.AlterField(
            model_name='register',
            name='profile',
            field=models.ImageField(null=True, upload_to='static/userpic/'),
        ),
    ]
