# Generated by Django 3.2.4 on 2023-09-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20230913_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproduct',
            name='veg_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
